// Sound-effects wrapper. The rest of the app calls `audio.play("place")` against
// this typed facade rather than touching expo-audio directly, so there is one
// place to manage the clip taxonomy, lazy player creation, and the mute toggle.
//
// NOTE: this module imports expo-audio (RN-only). Keep it out of `src/game/*` so
// the headless Node tests stay framework-free (same rule as `src/analytics`).
//
// Behaviour mirrors the haptics pattern in GameScreen: native-only, every call
// is a safe no-op on web / before init / when muted, and failures are swallowed
// so audio can never break gameplay. SFX clips live in `assets/audio/*.wav` and
// are regenerated by `scripts/make_sfx.py` — swap in designed clips anytime,
// just keep the filenames in `SOURCES` below.

import { Platform } from "react-native";

import type { AudioPlayer } from "expo-audio";

/** Every sound effect in the app. Add new cues here to keep them in one place. */
export type SoundName = "place" | "mark" | "mistake" | "win" | "fail" | "button";

// Static requires so Metro bundles the assets (the `require`s must be literal).
const SOURCES: Record<SoundName, number> = {
  place: require("../../assets/audio/place.wav"),
  mark: require("../../assets/audio/mark.wav"),
  mistake: require("../../assets/audio/mistake.wav"),
  win: require("../../assets/audio/win.wav"),
  fail: require("../../assets/audio/fail.wav"),
  button: require("../../assets/audio/button.wav"),
};

// expo-audio targets native; on web we no-op (the web build is a smoke-test
// target only, and there are no players to manage).
const enabled = Platform.OS !== "web";

let mod: typeof import("expo-audio") | null = null;
if (enabled) {
  // Loaded lazily so web builds don't pull in the native module.
  try {
    mod = require("expo-audio");
  } catch {
    mod = null;
  }
}

// One reusable player per clip, created on first use (cheap to keep resident —
// the clips are tiny). `seekTo(0)` before `play()` lets a cue retrigger rapidly.
const players = new Map<SoundName, AudioPlayer>();
let muted = false;
let configured = false;

function configure(): void {
  if (!mod || configured) return;
  configured = true;
  try {
    // Mix with other audio and respect the hardware silent switch — polite
    // defaults for incidental game SFX.
    void mod.setAudioModeAsync({
      playsInSilentMode: false,
      shouldPlayInBackground: false,
      interruptionMode: "mixWithOthers",
    });
  } catch {}
}

function get(name: SoundName): AudioPlayer | null {
  if (!mod) return null;
  let p = players.get(name);
  if (!p) {
    p = mod.createAudioPlayer(SOURCES[name]);
    players.set(name, p);
  }
  return p;
}

export const audio = {
  /** True when SFX can play (native, module loaded). */
  enabled: enabled && !!mod,

  /** Mute/unmute all SFX. Persisted by the caller (see useGame). */
  setMuted(value: boolean): void {
    muted = value;
  },

  get muted(): boolean {
    return muted;
  },

  /** Play a one-shot sound effect. Safe to call in any state. */
  play(name: SoundName): void {
    if (!mod || muted) return;
    try {
      configure();
      const p = get(name);
      if (!p) return;
      // Restart from the top so the cue fires even mid-playback.
      void p.seekTo(0);
      p.play();
    } catch {}
  },
};
